version: '3.9'

services:
  backend:
    build:
      context: ./backend
      args:
        APP_VERSION: ${APP_VERSION}  # Passa a variável para o build
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
