services:
backend:
  build: ./backend
  environment:
    - PORT=4000
    - APP_VERSION=${APP_VERSION}
  ports:
    - "4000:4000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
