name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.AWS_HOST }} << EOF
            cd ~/devops-demo || git clone https://github.com/${{ github.repository }} devops-demo
            cd devops-demo
            git reset --hard
            git pull origin master

            # Define a versão usando hash do commit
            export APP_VERSION=$(git rev-parse --short HEAD)

            docker-compose down

            # Passar o build-arg para o backend
            docker-compose build --no-cache --build-arg APP_VERSION=$APP_VERSION backend

            docker-compose up -d
          EOF
